---
title: "report 1 rdrs data"
author: "E.M.Thomas"
date: "2024-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(tidyverse)
library(here)
library(janitor)
library(stringr)
```



```{r}
setwd(here("raw data/CalRecycle/RDRS"))

# List all Excel files in your directory
excel_files <- list.files("report 1 data", pattern = "\\.xlsx$", full.names = TRUE)

# Create an empty list to store dataframes
dfs <- list()

# Loop through each Excel file, read it, and append to dfs list
for (file in excel_files) {
  df <- read_excel(file, sheet = 1)
  dfs[[file]] <- df
}

# Combine all dataframes into one
rdrs_combined_df <- bind_rows(dfs, .id = "file_name")
```

```{r}
rdrs_clean_df <- rdrs_combined_df %>% 
  clean_names() %>% 
  select(-file_name, -quarter, -jurisdiction) %>% 
  group_by(county, year) %>% 
  summarise(across(where(is.numeric), sum, na.rm = TRUE))  

rdrs_2019 <- rdrs_combined_df %>% 
  clean_names() %>% 
  filter(year == 2019) %>% 
  filter(quarter == 3 | quarter == 4) %>% 
  group_by(county, year) %>% 
  select(-file_name, -jurisdiction, -quarter) %>% 
  summarise(across(where(is.numeric), sum, na.rm = TRUE)) %>% 
  mutate(year = as.character(year)) %>% 
  mutate(across(where(is.numeric), ~ ./1.102))

rdrs_mt_df <- rdrs_clean_df %>%
  mutate(year = as.character(year)) %>% 
  mutate(across(where(is.numeric), ~ ./1.102))

rdrs_report_1 <- rbind(rdrs_2019, rdrs_mt_df)

```


```{r}
write_xlsx(rdrs_report_1, here("processed data/RDRS Report 1 Data Summarized_v2.xlsx"))
```


