---
title: "CalRecycle Plastic Fraction Comparison"
author: "E.M.Thomas"
date: "2024-05-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(tidyverse)
library(here)
library(janitor)
library(stringr)
library(writexl)
library(broom)
library(zoo)
```

```{r}
### Read in resin classification conversion table
resin_conversion_df <- read_excel(here("raw data/Resin Conversion.xlsx")) %>% 
  clean_names() %>% 
  rename(material_type = cal_recycle_classification) %>% 
  rename(resin_type = milbrandt_classification) 


### Read in 2004, 2008, 2014, 2018, and 2021 datasets
cal_waste_2004_df <- read_excel(here("raw data/CalRecycle/Disposal-based WCS/CalRecycle 2004 Statewide Disposal.xlsx")) %>% clean_names() %>% 
  select(1,3) %>% 
  rename(material_type = 1) %>% 
  mutate(estimated_tonnage = estimated_tonnage/1.102) #Convert short tons to metric tons

cal_waste_2008_df <- read_excel(here("raw data/CalRecycle/Disposal-based WCS/CalRecycle 2008 Statewide Disposal.xlsx")) %>% clean_names() %>% 
  select(1,3) %>% 
  rename(material_type = 1) %>% 
  mutate(estimated_tonnage = estimated_tonnage/1.102) #Convert short tons to metric tons

cal_waste_2014_df <- read_excel(here("raw data/CalRecycle/Disposal-based WCS/CalRecycle 2014 Statewide Disposal.xlsx")) %>% clean_names() %>% 
  select(1,3) %>% 
  rename(material_type = 1) %>% 
  mutate(estimated_tonnage = estimated_tonnage/1.102) #Convert short tons to metric tons

cal_waste_2018_df <- read_excel(here("raw data/CalRecycle/Disposal-based WCS/CalRecycle 2018 Statewide Disposal.xlsx")) %>% clean_names() %>% 
  select(1,3) %>% 
  rename(material_type = 1) %>% 
  mutate(estimated_tonnage = estimated_tonnage/1.102) #Convert short tons to metric tons

cal_waste_2021_df <- read_excel(here("raw data/CalRecycle/Disposal-based WCS/CalRecycle 2021 Statewide Disposal.xlsx")) %>% clean_names() %>% 
  select(1,3) %>% 
  rename(material_type = 1) %>% 
  mutate(estimated_tonnage = estimated_tonnage/1.102) #Convert short tons to metric tons
```


```{r}
resin_conversion_func <- function(cal_waste_df, resin_conversion_df) {
  resin_conversion <- resin_conversion_df$resin_type
  resin_material <- resin_conversion_df$material_type
  
  # Assign the milbrandt resin classifications to each material type  
  cal_waste_df$resin_conversion <- sapply(cal_waste_df$material_type, function(mat) {
    resin <- resin_conversion[resin_material == mat]
    if (length(resin) > 0) {
      return(resin)
    } else {
      return("Other")
    }
  })
  
  # Preparing for resin conversion
  df <- cal_waste_df %>%
    pivot_wider(names_from = resin_conversion, values_from = estimated_tonnage, values_fill = 0) %>%
    select(-material_type) %>%
    mutate(across(everything(), as.numeric)) %>% 
    summarise_all(sum) %>% 
    rename(pet = PETbc, hdpe = HDPEbc) %>% 
    clean_names()
  
  # Initialize missing columns with zero if they don't exist
  if (!"pp" %in% colnames(df)) df$pp <- 0
  if (!"mp" %in% colnames(df)) df$mp <- 0
  if (!"fwb" %in% colnames(df)) df$fwb <- 0
  if (!"dp" %in% colnames(df)) df$dp <- 0
  if (!"rc" %in% colnames(df)) df$rc <- 0
  
  # Apply resin conversion formulas to new dataframe
  resin_df <- data.frame(
    PET = df$pet + df$dp * 0.046 + df$rc * 0.08,
    HDPE = df$hdpe + df$fwb * 0.17 + df$dp * 0.114 + df$rc * 0.12,
    PP = df$pp + df$mp * 0.65 + df$fwb * 0.1 + df$dp * 0.336 + df$rc * 0.30,
    LDPE_LLDPE = df$mp * 0.1 + df$fwb * 0.69 + df$dp * 0.15 + df$rc * 0.18,
    PVC = df$mp * 0.025 + df$fwb * 0.013 + df$dp * 0.018 + df$rc * 0.036,
    Other_Resins = df$dp * 0.279 + df$rc * 0.194,
    PS = df$mp * 0.225 + df$fwb * 0.027 + df$dp * 0.057 + df$rc * 0.09
  )
  
  return(resin_df)
}

converted_2004_df <- resin_conversion_func(cal_waste_df = cal_waste_2004_df, resin_conversion_df = resin_conversion_df)

converted_2008_df <- resin_conversion_func(cal_waste_df = cal_waste_2008_df, resin_conversion_df = resin_conversion_df)

converted_2014_df <- resin_conversion_func(cal_waste_df = cal_waste_2014_df, resin_conversion_df = resin_conversion_df)

converted_2018_df <- resin_conversion_func(cal_waste_df = cal_waste_2018_df, resin_conversion_df = resin_conversion_df)

converted_2021_df <- resin_conversion_func(cal_waste_df = cal_waste_2021_df, resin_conversion_df = resin_conversion_df)

# Combine into one dataframe
converted_resin_final_df <- bind_rows(
  converted_2021_df,
  converted_2018_df,
  converted_2014_df,
  converted_2008_df,
  converted_2004_df,
)

rownames(converted_resin_final_df) <- c(2021, 2018, 2014, 2008, 2004) 

converted_resin_final_df <- data.frame(Year = rownames(converted_resin_final_df), converted_resin_final_df, row.names = NULL)

```


```{r}
write_xlsx(converted_resin_final_df, here("processed data/Converted WCS Resin Data Benchmark Years.xlsx")) 
```

## Interpolate between the years 
```{r}
# Ensure the Year column is numeric in the existing dataframe
converted_resin_final_df <- converted_resin_final_df %>%
  mutate(Year = as.numeric(Year))

# Create a dataframe with the additional years
additional_years_df <- tibble(Year = 2005:2021)

# Combine the existing dataframe with the additional years dataframe and remove duplicates
resin_interpolated_df <- bind_rows(converted_resin_final_df, additional_years_df) %>%
  distinct(Year, .keep_all = TRUE) %>%  # Remove duplicate years
  arrange(desc(Year)) %>%  # Arrange in ascending order for interpolation
  mutate(across(-Year, ~ na.approx(., x = Year, na.rm = FALSE)))  # Apply interpolation

```


```{r}
write_xlsx(resin_interpolated_df, here("processed data/Converted WCS Resin Data Interpolated 2005-2021.xlsx"))
```


