---
title: "business group material type data"
author: "E.M.Thomas"
date: "2024-06-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(tidyverse)
library(here)
library(janitor)
library(stringr)
library(writexl)
```


# Read in data, webscraped in Python 
```{r}
# url:https://www2.calrecycle.ca.gov/WasteCharacterization/BusinessGroupStreams?lg=1001&cy=1

bg_material_type_df_raw <- read.csv(here("processed data/Business Group EOL Stream by Material Type.csv")) %>% 
  clean_names()

### Read in resin classification conversion table
resin_conversion_df <- read_excel(here("raw data/Resin Conversion.xlsx")) %>% 
  clean_names() %>% 
  rename(material_type = cal_recycle_classification) %>% 
  rename(resin_type = milbrandt_classification) 
```


```{r}
# remove unneeded columns, separate out multifamily units
bg_material_type_df_clean <- bg_material_type_df_raw %>% 
  select(county, business_group_name, material_type, employee_count, tons_curbside_organics, tons_curbside_recycle, tons_other_diversion, tons_disposed, tons_total_generation) %>% 
  filter(business_group_name != "Multifamily")  %>%
  mutate(across(starts_with("tons"), ~ .x / 1.102))

# maybe multifamily proportions can be used to estimate single family residences?
multifamily_material_type_df <- bg_material_type_df_raw %>% 
  select(county, business_group_name, material_type, occupied_multifamily_units, tons_curbside_organics, tons_curbside_recycle, tons_other_diversion, tons_disposed, tons_total_generation) %>% 
  filter(business_group_name == "Multifamily")  %>%
  mutate(across(starts_with("tons"), ~ .x / 1.102))
  
```

# Convert Material Type to Resin Type
```{r}
### Read in resin classification conversion table
resin_conversion_df <- read_excel(here("raw data/Resin Conversion.xlsx")) %>% 
  clean_names() %>% 
  rename(material_type = cal_recycle_classification) %>% 
  rename(resin_type = milbrandt_classification) 

# Remove unneeded columns
bg_material_type_df_clean <- bg_material_type_df_raw %>% 
  select(county, business_group_name, material_type, tons_curbside_organics, tons_curbside_recycle, tons_other_diversion, tons_disposed, tons_total_generation) %>%
  mutate(across(starts_with("tons"), ~ .x / 1.102))

# Convert Material Type to Resin Type
resin_conversion_func_new <- function(bg_material_type_df, resin_conversion_df) {
  resin_conversion <- resin_conversion_df$resin_type
  resin_material <- resin_conversion_df$material_type
  
  # Assign the milbrandt resin classifications to each material type  
  bg_material_type_df$resin_conversion <- sapply(bg_material_type_df$material_type, function(mat) {
    resin <- resin_conversion[resin_material == mat]
    if (length(resin) > 0) {
      return(resin)
    } else {
      return("Other")
    }
  })
  
  # Function to process each column
  process_column <- function(column_name) {
    df <- bg_material_type_df %>%
      select(county, business_group_name, resin_conversion, all_of(column_name)) %>%
      group_by(county, business_group_name,  resin_conversion) %>%
      summarise(value = sum(.data[[column_name]], na.rm = TRUE), .groups = "drop") %>%
      pivot_wider(names_from = resin_conversion, values_from = value, values_fill = list(value = 0)) %>%
      ungroup() %>%
      mutate(across(!c(county, business_group_name), as.numeric)) %>% 
      rename(pet = PETbc, hdpe = HDPEbc) %>% 
      clean_names()
    
    # Initialize missing columns with zero if they don't exist
    if (!"pp" %in% colnames(df)) df$pp <- 0
    if (!"mp" %in% colnames(df)) df$mp <- 0
    if (!"fwb" %in% colnames(df)) df$fwb <- 0
    if (!"dp" %in% colnames(df)) df$dp <- 0
    if (!"rc" %in% colnames(df)) df$rc <- 0
    
    df <- df %>%
      mutate(
        PET = pet + dp * 0.046 + rc * 0.08,
        HDPE = hdpe + fwb * 0.17 + dp * 0.114 + rc * 0.12,
        PP = pp + mp * 0.65 + fwb * 0.1 + dp * 0.336 + rc * 0.30,
        LDPE_LLDPE = mp * 0.1 + fwb * 0.69 + dp * 0.15 + rc * 0.18,
        PVC = mp * 0.025 + fwb * 0.013 + dp * 0.018 + rc * 0.036,
        Other_Resins = dp * 0.279 + rc * 0.194,
        PS = mp * 0.225 + fwb * 0.027 + dp * 0.057 + rc * 0.09
      ) %>%
      select(county, business_group_name, PET, HDPE, PP, LDPE_LLDPE, PVC, Other_Resins, PS) %>%
      mutate(ton_type = column_name)  # Add the ton type as a column
    
    return(df)
  }
  
  # Process each column and combine results
  columns_to_process <- c("tons_curbside_organics", "tons_curbside_recycle", "tons_other_diversion", "tons_disposed")
  results_list <- lapply(columns_to_process, process_column)
  
  combined_results <- bind_rows(results_list)
  
  return(combined_results)
}

# Apply the function to your new dataframe
bg_resin_df <- resin_conversion_func_new(bg_material_type_df_clean, resin_conversion_df)
```

```{r}
#write_xlsx(bg_resin_df, here("processed data/WCS Business Group by Resin_240701.xlsx"))
```




